### ISSUE TITLE
Adding a PR template to the repository 

### ISSUE THREAD

**Issue by Bisht13** [ykarim/openmrs-contrib-gci-site#17]
Instead of making wage PRs and writing the format again and again. It's better to have a PR template for the repository.

**Comment by Bisht13** [comment]
Working on it 😄

**Comment by ykarim** [comment]
I thought about this earlier, but don't really see the need (at least for now) as the repo is more than just code and there's not much going into PR descriptions maybe an issue template would help though. For like bug reports and such like What happened? What was the expected behavior? Any logs etc. Closing this for now
